spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dgs-lab
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update
    show-sql: true
    generate-ddl: true
  cache:
    type: redis

  kafka:
    bootstrap-servers: http://localhost:29092
  artemis:
    embedded:
      topics: test.topic